export const ACTION_ITEMS = {
  LOGIN_REQUEST:'LOGIN_REQUEST',
  LOGIN_SUCCESS:'LOGIN_SUCCESS',
  LOGIN_FAILURE:'LOGIN_FAILURE',
  SEARCH_REQUEST:'SEARCH_REQUEST',
  SEARCH_SUCCESS:'SEARCH_SUCCESS',
  SEARCH_FAILURE:'SEARCH_FAILURE',
  LOGOUT:'LOGOUT'
}